name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun run build

      - uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            main.js
            manifest.json
            styles.css
